---
name: Docker Image CI

on:
  push:
    branches: [ "master", "dockerfile" ]
  pull_request:
    branches: [ "master", "dockerfile" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        # We use `git describe` later, so need 'all'
        fetch-depth: 0
        sparse-checkout-cone-mode: false
        fetch-tags: true

    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v3.10.0
      with:
        platforms: "linux/arm64,linux/arm,linux/amd64"

    - name: Login to DockerHub
      uses: docker/login-action@v3.4.0
      with:
        username: number27
        password: ${{ secrets.DOCKERHUB_PAT }}

    - name: Build the Docker image
      run: |
        git remote add upstream "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/atauenis/webone.git"
        git fetch upstream --tags --quiet
        git remote -v
        export IMG_TAG=$(git describe --always --broken --tags --first-parent --abbrev)
        echo "Current version from git: $IMG_TAG"

        docker buildx build \
          --pull --push \
          --platform "linux/arm64,linux/arm,linux/amd64" \
          -t docker.io/number27/webone:latest \
          -t docker.io/number27/webone:$IMG_TAG \
          .
