---
name: Docker Image CI

on:
  push:
    branches: [ "master", "dockerfile" ]
  pull_request:
    branches: [ "master", "dockerfile" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Docker Setup Buildx
      # You may pin to the exact commit or the version.
      # uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2
      uses: docker/setup-buildx-action@v3.10.0
      with:
        # Fixed platforms for current node. If not empty, values take priority over the detected ones
        platforms: "linux/arm64,linux/arm,linux/amd64"
        # Append additional nodes to the builder
        # append: # optional              

    - name: Build the Docker image
      run: docker buildx build --pull --platform "linux/arm64,linux/arm,linux/amd64" -t number27/webone:latest .
      # run: docker build . --file Dockerfile --tag number27/webone:$(date +%s) --tag number27/webone:dev --tag number27/webone:latest
    - name: Publish to the Docker Hub
      run: docker push number27/webone:latest
